// Pack bot-source.ts into the rows _bot_code holds, as runnable SQL.
//
// The loader reads `_bot_code` ordered by `part` and concatenates `content`,
// so the parts must be written in order and nothing may be left behind from a
// longer previous blob — hence the delete inside the same transaction.
//
//   node tools/pack.mjs            # writes deploy/_bot_code.sql
//   node tools/pack.mjs --verify   # only checks the blob inflates back
import { readFileSync, writeFileSync } from "node:fs";
import { gzipSync, gunzipSync } from "node:zlib";

const PART_CHARS = 4000;
const src = readFileSync(new URL("../bot-source.ts", import.meta.url));

// mtime 0 keeps the output byte-identical between runs, so a regenerated file
// diffs as empty when the source has not changed.
const b64 = gzipSync(src, { level: 9, mtime: 0 }).toString("base64");

if (gunzipSync(Buffer.from(b64, "base64")).equals(src)) {
  console.log(`roundtrip ok — ${src.length} B source, ${b64.length} B base64`);
} else {
  console.error("roundtrip FAILED — refusing to emit SQL");
  process.exit(1);
}

const parts = [];
for (let i = 0; i < b64.length; i += PART_CHARS) parts.push(b64.slice(i, i + PART_CHARS));
console.log(`${parts.length} parts of up to ${PART_CHARS} chars`);
if (process.argv.includes("--verify")) process.exit(0);

// Base64 contains no quotes, so the literals below need no escaping.
const sql = [
  "-- GENERATED by tools/pack.mjs — do not edit by hand.",
  "-- Regenerate with:  node tools/pack.mjs",
  "--",
  "-- Paste into the Supabase SQL editor of project zqpglkxbtpkvyraxquao, then",
  "-- hit telegram-bot?health=1 and check that loaded_from is _bot_code.",
  "begin;",
  "delete from _bot_code;",
  "insert into _bot_code (part, content) values",
  parts.map((p, i) => `  (${i + 1}, '${p}')`).join(",\n") + ";",
  "commit;",
  "",
].join("\n");

writeFileSync(new URL("../deploy/_bot_code.sql", import.meta.url), sql);
console.log("wrote deploy/_bot_code.sql");
